[2025-02-08T12:21:40.225+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:21:23.757711+00:00 [queued]>
[2025-02-08T12:21:40.239+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:21:23.757711+00:00 [queued]>
[2025-02-08T12:21:40.240+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:21:40.240+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T12:21:40.240+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:21:40.250+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): upload_to_elasticsearch> on 2025-02-08 12:21:23.757711+00:00
[2025-02-08T12:21:40.272+0000] {standard_task_runner.py:52} INFO - Started process 607 to run task
[2025-02-08T12:21:40.276+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'upload_to_elasticsearch', 'manual__2025-02-08T12:21:23.757711+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpzcvd9q3_', '--error-file', '/tmp/tmpepyyfdfi']
[2025-02-08T12:21:40.277+0000] {standard_task_runner.py:80} INFO - Job 17: Subtask upload_to_elasticsearch
[2025-02-08T12:21:40.338+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:21:23.757711+00:00 [running]> on host fac8a5123a60
[2025-02-08T12:21:40.403+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Azka
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=upload_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T12:21:23.757711+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T12:21:23.757711+00:00
[2025-02-08T12:21:40.461+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 96, in upload_to_elasticsearch
    helpers.bulk(Elasticsearch, actions)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 411, in bulk
    client, actions, ignore_status=ignore_status, *args, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 320, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
AttributeError: type object 'Elasticsearch' has no attribute 'transport'
[2025-02-08T12:21:40.474+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=upload_to_elasticsearch, execution_date=20250208T122123, start_date=20250208T122140, end_date=20250208T122140
[2025-02-08T12:21:40.480+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task upload_to_elasticsearch (type object 'Elasticsearch' has no attribute 'transport'; 607)
[2025-02-08T12:21:40.497+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T12:21:40.518+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
