[2025-02-08T12:26:27.015+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:26:08.948392+00:00 [queued]>
[2025-02-08T12:26:27.022+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:26:08.948392+00:00 [queued]>
[2025-02-08T12:26:27.022+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:26:27.022+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T12:26:27.022+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T12:26:27.029+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): upload_to_elasticsearch> on 2025-02-08 12:26:08.948392+00:00
[2025-02-08T12:26:27.034+0000] {standard_task_runner.py:52} INFO - Started process 658 to run task
[2025-02-08T12:26:27.036+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'upload_to_elasticsearch', 'manual__2025-02-08T12:26:08.948392+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp03o4ag2e', '--error-file', '/tmp/tmp4e49de6e']
[2025-02-08T12:26:27.037+0000] {standard_task_runner.py:80} INFO - Job 20: Subtask upload_to_elasticsearch
[2025-02-08T12:26:27.082+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.upload_to_elasticsearch manual__2025-02-08T12:26:08.948392+00:00 [running]> on host fac8a5123a60
[2025-02-08T12:26:27.131+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Azka
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=upload_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T12:26:08.948392+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T12:26:08.948392+00:00
[2025-02-08T12:26:27.140+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 80, in upload_to_elasticsearch
    df_cleaned = pd.read_csv(cleaned_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2025-02-08T12:26:27.155+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=upload_to_elasticsearch, execution_date=20250208T122608, start_date=20250208T122627, end_date=20250208T122627
[2025-02-08T12:26:27.165+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task upload_to_elasticsearch (Invalid file path or buffer object type: <class 'NoneType'>; 658)
[2025-02-08T12:26:27.174+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T12:26:27.204+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
